### ISSUE TITLE
synthetic_text_gen

### ISSUE THREAD

**Issue by ArsalanAli915** [herobd/dessurt#8]
2023-02-27 16:48:56.505009: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-27 16:48:56.505147: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-27 16:48:56.505167: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
loaded iteration 0
unspecified dataset: /content/drive/MyDrive/dataset/MDdata/valid/SKMBT_75122072616550_Page_45_Image_0001.png
getting data ready
could not import datasets
Traceback (most recent call last):
  File "qa_eval.py", line 595, in <module>
    main(args.checkpoint, args.data_set_name, gpu=args.gpu, config=args.config, addToConfig=addtoconfig,test=args.test,verbose=args.verbosity,run=run,smaller_set=args.smaller_set,eval_full=args.eval_full,ner_do_before=args.ner_do_before)
  File "qa_eval.py", line 419, in main
    data_loader, valid_data_loader = getDataLoader(data_config,'train' if not test else 'test')
  File "/content/dessurt/data_loader/data_loaders.py", line 36, in getDataLoader
    from data_sets import multiple_dataset
  File "/content/dessurt/data_sets/multiple_dataset.py", line 16, in <module>
    from .synth_form_dataset import SynthFormDataset
  File "/content/dessurt/data_sets/synth_form_dataset.py", line 11, in <module>
    from .gen_daemon import GenDaemon
  File "/content/dessurt/data_sets/gen_daemon.py", line 4, in <module>
    from synthetic_text_gen import SyntheticWord
ModuleNotFoundError: No module named 'synthetic_text_gen'

I am facing above error when I run eval.py to evaluate the dataset

**Comment by ArsalanAli915** [comment]
when I train the model I found that, entire training is completed and there is no epoch numbers and metrics display. except that begin training. In addition to that when I evaluate the model. I found that mean and std deviation of edit distance and not WER or CER. please help me.

**Comment by herobd** [comment]
synthetic_text_gen can be found here https://github.com/herobd/synthetic_text_gen
(although I'd imagine it's not needed for what your doing. You could also comment imports out)

I'm sure exactly what you're asking with your second comment. Does it not train?

**Comment by ArsalanAli915** [comment]
Downloading (…)olve/main/vocab.json: 100%
899k/899k [00:00<00:00, 2.92MB/s]
Downloading (…)olve/main/merges.txt: 100%
456k/456k [00:00<00:00, 1.84MB/s]
Downloading (…)lve/main/config.json: 100%
1.72k/1.72k [00:00<00:00, 62.9kB/s]
Downloading (…)"pytorch_model.bin";: 100%
558M/558M [00:05<00:00, 87.3MB/s]
/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Begin training


When I train model I found above thing and cell keep running and at some point my system crashes. please guide what I doing wrong. There is no epoch number etc to shown while model is training.

**Comment by ArsalanAli915** [comment]
could we have meetiing if possible on zoom etc. I really need help.

**Comment by ArsalanAli915** [comment]
Thank for replying and helping me out.
I just need to ask one more question.
my result are shown in edit  distance and ANLS.
if I want the character error rate or or word error rate then what I need to change in config file. please let me know it would really helpful.

**Comment by herobd** [comment]
If you run qa_eval.py using the trained model it produces CER/WER for recognition datasets
`python qa_eval.py -c CHECKPOINT.pth -d DATASETNAME [-g GPU#] [-T (do test set)]`
If it is a custom dataset you will need to modify things a bit so it treats your dataset as a recognition dataset.
